apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-deployment
  labels:
    app: dotnet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: dotnet
        image: zippyops01/dotnetlinux:latest
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: dotnet-service
spec:
  selector:
    app: dotnet
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30127
  type: LoadBalancer       
